server {
    listen 80;
    server_name meshtah.net www.meshtah.net;
    return 301 https://meshtah.net$request_uri;
}

server {
    listen 443 ssl http2;
    server_name meshtah.net www.meshtah.net;

    ssl_certificate     /etc/letsencrypt/live/meshtah.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/meshtah.net/privkey.pem;

    location /api/ {
        proxy_pass http://strapi:80/;
    }

    location /uploads/ {
        proxy_pass http://strapi:80/uploads/;
    }

    location /admin {
        proxy_pass http://strapi:80/admin/;
    }

    location / {
        proxy_pass http://next:3000/;
    }
}